### GENERAL SETTINGS ###

# Site settings
title: ToyChurros.
description: "Character & Toy design studio in South Korea."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://www.toychurros.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#F68827" #"#F70031" 
  primary_rgb: "246,136,39" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#282828" #"#33004D"
  link: "#F68827"
  link_hover: "#dd7c29"
  footer_heading: "#ffffff"
  footer_content: "#d4c9c1"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: dribbble
    url:
  - title: facebook
    url:
  - title: twitter
    url: 
  - title: instagram
    url: 
  - title: tumblr
    url: 
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - ClusterCenter 4F KnowledgeFactory, Hanyangdaehak-ro 55,
    - Sangrok-gu, Ansan-si, Gyeonggi-do,
    - South Korea.
email: ido0114@naver.com
tel: +82 10-4259-0987


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Jeong Seungho
    position: CEO/ToyDesigner
    text: ToyChurros team leader. 3d printing toy designer.
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:ido0114@naver.com
      - title: facebook
        url: https://www.facebook.com/ido0114
  - name: Kim Hyemin
    position: Illustrator
    text: Little fairy character 'GGOYO' designer.
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:hellow16@naver.com
      - title: facebook
        url: https://www.facebook.com/hyemin.kim.969
  - name: Jo Dukeray
    position: Cartoonist
    text: Social satire character 'PIK' designer.
    img: team03.jpg
    social:
      - title: envelope #use for email address
        url: mailto:emrfo123@naver.com
      - title: facebook
        url: https://www.facebook.com/jo.dukeray
  - name: Choi Eunji
    position: Character Designer
    text: Welsh corgi character 'BORI' designer.
    img: team04.jpg
    social:
      - title: envelope #use for email address
        url: mailto:cozjd@naver.com
      - title: facebook
        url: https://www.facebook.com/cozjd
    
# Clients information. Shown on Home and About pages.
clients:
  - name: LINE
    img: client_line.png
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "캐릭터 & 토이 디자인 스튜디오"

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "토이츄러스는 4가지의 각기 다른 캐릭터를 보유하고 있습니다. 각각 작가의 개성이 드러난 캐릭터로 다양한 분야에 활용 할 수 있습니다. 현재 해당 캐릭터로 3D프린팅 토이, 풍자만화, 일러스트작품 등을 제작하고있습니다. 현재 커플전용메신저 비트윈과 LINE 에 이모티콘 상품이 입점된 상태입니다."
    author: 토이츄러스
    position: www.toychurros.com